service: icon-app-ui
frameworkVersion: ^3.3.0

provider:
  name: aws
  runtime: nodejs14.x
  stage: ${opt:stage,'qa'}
  region: ${opt:region,'sa-east-1'}
  memorySize: 256
  # profile: default

plugins:
  - serverless-s3-sync
  - serverless-prune-plugin

custom:
  siteName: icon-app-ui-${opt:stage,'qa'}
  s3Sync:
    - bucketName: ${self:custom.siteName}
      localDir: build
#  aliasHostedZoneId: us-east-1
#  aliasDNSName: s3-website-us-east-1.amazonaws.com

resources:
  Resources:
    StaticSite:
      Type: AWS::S3::Bucket
      Properties:
        AccessControl: PublicRead
        BucketName: ${self:custom.siteName}
        WebsiteConfiguration:
          IndexDocument: index.html

    StaticSiteS3BucketPolicy:
      Type: AWS::S3::BucketPolicy
      Properties:
        Bucket:
          Ref: StaticSite
        PolicyDocument:
          Statement:
            - Sid: PublicReadGetObject
              Effect: Allow
              Principal: "*"
              Action:
                - s3:GetObject
              Resource:
                Fn::Join: ["", ["arn:aws:s3:::", { "Ref": "StaticSite" }, "/*"]]
    # DnsRecord:
    #   Type: "AWS::Route53::RecordSet"
    #   Properties:
    #     AliasTarget:
    #       DNSName: ${self:custom.aliasDNSName}
    #       HostedZoneId: ${self:custom.aliasHostedZoneId}
    #     HostedZoneName: ${self:custom.siteName}.
    #     Name:
    #       Ref: StaticSite
    #     Type: 'A'