module.exports.swot_oportunidades = [
    "Acesso a fontes de financiamentos do governo",
    "Adequar negócio para atender órgãos governamentais",
    "Atrair investidores para alavancagem do negócio",
    "Atualização tecnológica em ambiente digital",
    "Aumentar competências organizacionais",
    "Automação das rotinas administrativas",
    "Automação para indústria 4.0",
    "Capacitação dos colaboradores através do sistema S",
    "Desenvolver novos produtos e/ou serviços",
    "Desenvolver parcerias internacionais",
    "Desenvolver soluções por perfil socioeconômico de clientes",
    "Fusões & Aquisições (M&A)",
    "Importação de produtos, insumos ou máquinas",
    "Incorporar as novas tecnologias emergentes",
    "Inovar modelo de negócios/reposicionamento no mercado",
    "Melhorar modelo de governança",
    "Ofecer soluções adequada as novas tendências culturais",
    "Parceria com startups tecnológicas",
    "Realizar hedge cambial",
    "Redução de custos de folha com flexibilização trabalhista",
    "Redução de custos por simplificação tributária",
    "Regularização a legislação vigente",
    "Segmentação de clientes e mercado",
    "Substituição de materiais e/ou serviços por inovação",
].sort()

module.exports.swot_ameacas = [
    "Aumento de custos pela valorização cambial",
    "Perda de receita pelo alto no desemprego/recessão econômica",
    "Queda de Receitas",
    "Não acessar recursos de investimentos para atualização tecnológica",
    "Multas por não atender legislação",
    "Processos trabalhistas",
    "Perda de colaboradores chave para o mercado",
    "Carga tributária inviabiliza rentabilidade mínima",
    "Multas pela receita federal",
    "Tempo excessivo para importação",
    "Obsolescência dos produtos ou serviços",
    "Perda de mercado por substituição tecnológica",
    "Perda de competitividade para produtos importados",
    "Falta de estrutura/recursos nos projetos estratégicos",
    "Pressão nos custos de insumos",
    "Falta de mão de obra qualificada",
    "Resistência cultural as mudanças necessárias",
    "Não atender demanda das novas gerações",
    "Necessidade de altos investimentos",
].sort()

module.exports.fatores = [
    'Cambio',
    'Tecnologia',
    'Legislação',
    'Demografia - Envelhecimento',
    'Cultural',
    'Economia',
    'Globalização',
    'Pandemia',
    'Politica',
    'Social'
].sort()